spring.application.name=equipmentrental

# Aiven MySQL
spring.datasource.url=jdbc:mysql://mysql-1b3b3ddb-agri-equipment-rental.b.aivencloud.com:11325/equipment_rental?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=${PORT:8081}

# Brevo Email API
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=Agricultural Equipment Rental